# Generated by Django 3.2.7 on 2021-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('product_name', models.CharField(max_length=120)),
                ('product_details', models.CharField(max_length=300)),
                ('contact_number', models.IntegerField()),
                ('product_pic', models.ImageField(upload_to='Images/')),
                ('product_price', models.FloatField()),
                ('product_stock', models.IntegerField()),
            ],
        ),
    ]
