# Generated by Django 3.2.7 on 2021-10-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_pic',
        ),
        migrations.AlterField(
            model_name='item',
            name='contact_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_details',
            field=models.TextField(max_length=1000),
        ),
    ]
