# Generated by Django 3.2.7 on 2021-10-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellItem', '0002_auto_20211004_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact_number',
            field=models.IntegerField(default=None),
        ),
    ]
