# Generated by Django 3.2.7 on 2021-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellItem', '0003_auto_20211004_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_url',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
