# Generated by Django 3.2.7 on 2021-10-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellItem', '0005_alter_item_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
