# Generated by Django 3.2.7 on 2021-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellItem', '0006_auto_20211004_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_url',
        ),
        migrations.AlterField(
            model_name='item',
            name='product_pic',
            field=models.FileField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
