# Generated by Django 3.2.7 on 2021-10-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemforHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_details', models.TextField(max_length=1000)),
                ('contact_number', models.IntegerField(default=None)),
                ('product_pic', models.FileField(blank=True, null=True, upload_to='Images/')),
                ('product_price', models.FloatField()),
                ('product_stock', models.IntegerField()),
                ('product_condition', models.CharField(max_length=120)),
                ('hire_duration', models.DurationField()),
                ('product_location', models.CharField(max_length=50)),
            ],
        ),
    ]
